name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run some command
        run: echo "Hello, GitHub Actions!"

jobs:
  test:
    steps:
      - name: 23f3001480@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      
